Adds docker-compose
gr8web/task-manager pull request #1
Opened 2021-09-20 22:29 UTC by gr8web

2021-09-21 16:02 UTC, greybutton requested changes
нужно создать ветку develop, и от нее создавать ветки и в нее же сливать. develop основная ветка разработки

2021-09-22 18:52 UTC, gr8web commented
> нужно создать ветку develop, и от нее создавать ветки и в нее же сливать. develop основная ветка разработки

добавил develop

2021-09-22 19:55 UTC, greybutton approved these changes
отправь в обучалке еще раз на проверку, чтобы там отметить завершенным

2021-09-23 18:12 UTC, greybutton commented
после аппрува на гитхабе можно мержить)

2021-09-23 18:14 UTC, gr8web commented
ok, thx.

2021-09-23 18:15 UTC, merged